# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0003_auto_20161025_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
