# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0006_auto_20161026_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessagestatus',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermessagestatus',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Sent'), (1, 'Sent')], default=1),
        ),
    ]
